sample_name: 'sample'

fast5_parent_dir: '/home/elimoss/minION_data/fast5/9-7-18_p2-15mo_sample/20180904_2143_9-4-18_p2-15mo'
fast5_dirs_list: 'fodn.txt' #list of absolute paths to run/fast5/* subfolders containing .fast5 files
flowcell: 'FLO-MIN106'
kit: 'SQK-LSK109'
short_reads: '' #Comma-separated forward and reverse optionally gzipped fastq files.  Optional.  If no reads are given, the pilon step is skipped.
singularity: "shub://elimoss/metagenomics_workflows:longread"

#the below options are all related to Canu
canu_args: '' 
usegrid: 'True' #should Canu use the grid?
grid_options: '--time=6:00:00 --account asbhatt'
genome_size: '50m,100m'
