sample_name: 'sample'
fast5_dirs_list: 'fodn.txt' #list of absolute paths to run/fast5/* subfolders containing .fast5 files
flowcell: 'FLO-MIN106'
kit: 'SQK-LSK109'
genome_size: '50m,100m'
grid_options: '--time=6:00:00 --account asbhatt'
usegrid: 'True' #should canu use the grid?
short_reads: '' #Comma-separated forward and reverse optionally gzipped fastq files.  Optional.  If no reads are given, the pilon step is skipped.