sample_name: 'sample'

#data input
fast5_directory: '/path/to/fast5/data/'
flowcell: 'FLO-MIN106'
kit: 'SQK-LSK109'

#workflow steps to perform
min_contig_size: 0 #remove contigs smaller than this from the assembly (can speed up polishing but potentially hurt genome completeness)
skip_circularization: False
skip_polishing: False
polish_both: False #should the input to short read polishing be the output of long read polishing?
short_reads: '' #Comma-separated forward and reverse optionally gzipped fastq files.  Optional.  If no reads are given, the pilon step is skipped.

#the below options are all related to Canu
canu_args: 'cnsThreads=2 cnsMemory=32'
usegrid: True #should Canu use the grid?
grid_options: '--time=80:00:00 --account asbhatt'
genome_size: '50m,100m'
