name: mgwf
channels:
  - bioconda
  - defaults
  - conda-forge
  - ursky
dependencies:
  - snakemake
  - r-circlize
  - prodigal
  - checkm-genome
  - aragorn
  - metabat2
  - barrnap
  - quast
  - prokka
  - samtools
  - ncurses
  - bedtools
  - kraken
  - bwa
  - pip:
    - pysam
    - numpy
